name: tii-depthai-ctrl

on:
  repository_dispatch:
    types: [fog-ros-baseimage-update]
  push:
    branches: main
    tags:
      - 'v*'
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+
  pull_request:
    branches: [ main ]

jobs:
  tii-depthai-ctrl:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:

      - name: Checkout depthai_ctrl
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: docker/setup-buildx-action@v1

      - name: Set image tag format without suffix
        run: |
          echo "IMAGE_TAG_FORMAT=type=sha" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: Set image tag format with suffix
        # it is possible that run_number should be used instead run_attempt
        # run_attempt is unique number on every run and run_attempt resets to 1 if re-build is not used
        # content of image_sha_tag_suffix is defined in fog-ros-baseimage dispater workflow.
        run: |
          echo "IMAGE_TAG_FORMAT=type=sha,suffix=-${{ github.event.client_payload.image_sha_tag_suffix }}" >> $GITHUB_ENV
        if: github.event_name == 'repository_dispatch'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build the builder container image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.build_env
          push: true
          tags: localhost:5000/tiiuae/depthai_ctrl:build_env
          build-args: |
            PACKAGE_NAME=depthai_ctrl
            ROS_DISTRO=galactic

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/tiiuae/tii-depthai-ctrl
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=latest
            ${{ env.IMAGE_TAG_FORMAT }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tii-depthai-ctrl image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PACKAGE_NAME=depthai_ctrl
            ROS_DISTRO=galactic
            FROM_IMAGE=localhost:5000/tiiuae/depthai_ctrl:build_env
